export const CONFIG = Object.freeze({
  GRID_WIDTH: 180,
  GRID_HEIGHT: 80,
  TARGET_FPS: 60,
  PHYSICS_STEP_MS: 1000 / 60,
  DEFAULT_BRUSH_RADIUS: 5,
  MIN_BRUSH_RADIUS: 1,
  MAX_BRUSH_RADIUS: 5,
  FIRE_LIFETIME: 30,
  HOT_SAND_HOT_TICKS: 30,
  HOT_SAND_COOLDOWN_TICKS: 240,
  HOT_SAND_LIFETIME: 420,
  FIRE_SPREAD_CHAIN_STEPS: 3,
  GRAVITY_ACCELERATION: 72,
  OIL_GRAVITY_ACCELERATION: 112,
  GRAVITY_MAX_VELOCITY: 255,
  GRAVITY_HALF_SPEED_THRESHOLD: 128,
  GRAVITY_FULL_SPEED_THRESHOLD: 224,
  GRAVITY_INITIAL_PERIOD: 4,
  LIQUID_FULL_AMOUNT: 255,
  LIQUID_FREE_FALL_TRANSFER: 255,
  WATER_FREE_FALL_CHAIN_STEPS: 2,
  WATER_DIAGONAL_CHAIN_STEPS: 3,
  LIQUID_DIAGONAL_TRANSFER: 192,
  LIQUID_HORIZONTAL_TRANSFER: 192,
  LIQUID_PRESSURE_TRANSFER_FRACTION: 0.78,
  LIQUID_PRESSURE_MIN_TRANSFER: 24,
  WATER_RENDER_MIN_VISIBLE_AMOUNT: 8,
  WATER_RELAXATION_PASSES_MIN: 3,
  LIQUID_COLLIDING_RELAXATION_PASSES: 1,
  WATER_RELAXATION_PASSES_MAX: 12,
  WATER_RELAXATION_RAMP_TICKS: 180,
  OIL_FREE_FALL_CHAIN_STEPS: 2,
  OIL_DIAGONAL_CHAIN_STEPS: 2,
  OIL_BUOYANCY_CHAIN_STEPS: 4,
  OIL_RELAXATION_PASSES_MIN: 3,
  OIL_RELAXATION_PASSES_MAX: 9,
  OIL_RELAXATION_RAMP_TICKS: 180,
  LIQUID_EQUILIBRIUM_THRESHOLD: 12,
  COLORS: Object.freeze({
    // Packed as 0xAABBGGRR for the little-endian Uint32Array ImageData view.
    0: 0xff17250f,
    1: 0xff0b9ef5,
    2: 0xffc78402,
    3: 0xff871c58,
    4: 0xff4444ef,
  }),
  HOT_SAND_COLOR: 0xff0000ff,
  LIQUID_STATES: Object.freeze({
    NONE: 0,
    FALLING: 1,
    COLLIDING: 2,
    RESTING: 3,
    FLOWING: 4,
    SETTLING: 5,
  }),
  ELEMENTS: Object.freeze({
    ERASER: 0,
    SAND: 1,
    WATER: 2,
    OIL: 3,
    FIRE: 4,
  }),
});

export const ELEMENT_CONTEXT = Object.freeze([
  { id: 0, name: 'ERASER', description: 'Empty background space; clears target cells.' },
  { id: 1, name: 'SAND', description: 'Granular solid; falls, slides diagonally, and displaces lighter liquids.' },
  { id: 2, name: 'WATER', description: 'Liquid; falls, slides diagonally, and disperses horizontally.' },
  { id: 3, name: 'OIL', description: 'Viscous flammable liquid; floats on water and burns when touching fire.' },
  { id: 4, name: 'FIRE', description: 'Rising energy; ignites adjacent oil and decays into empty space.' },
]);
